version: '3.8'

services:
  postgres_showcase:
    image: postgres:latest
    container_name: postgres_showcase
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: showcase
    ports:
      - "5432:5432"
    volumes:
      - showcase_data:/var/lib/postgresql/data
    networks:
      - shop_network

  postgres_payment:
    image: postgres:latest
    container_name: postgres_payment
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paymentservice
    ports:
      - "5433:5432"
    volumes:
      - payment_data:/var/lib/postgresql/data
    networks:
      - shop_network

  showcase:
    build:
      context: .
      dockerfile: Dockerfile.showcase
    image: showcase
    container_name: showcase_app
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      - postgres_showcase
    environment:
      SPRING_DATASOURCE_URL: r2dbc:postgresql://postgres_showcase:5432/showcase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - shop_network

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile.payment
    image: payment-service
    container_name: payment_service_app
    working_dir: /app
    ports:
      - "8081:8081"
    depends_on:
      - postgres_payment
    environment:
      SPRING_DATASOURCE_URL: r2dbc:postgresql://postgres_payment:5432/paymentservice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - shop_network

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - shop_network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    command: start-dev
    ports:
      - "8090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - shop_network

networks:
  shop_network:
    driver: bridge

volumes:
  showcase_data:
  payment_data:
  keycloak_data:
