version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_shopdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shop_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: shop
    container_name: yandex_shop
    working_dir: /app
    command: [ "java", "-jar", "shop.jar" ]
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - shop_network

networks:
  shop_network:
    driver: bridge

volumes:
  postgres_data: