spring:
  application:
    name: payment-service

  datasource:
    url: r2dbc:postgresql://postgresql:5433/paymentservice
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/master

  main:
    allow-bean-definition-overriding: true

  sql:
    init:
      mode: always

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  port: 8081
